language: node_js
before_install:
 - deb http://ppa.launchpad.net/gijzelaar/cuda/ubuntu oneiric main
 - deb-src http://ppa.launchpad.net/gijzelaar/cuda/ubuntu oneiric main
 - deb http://ppa.launchpad.net/gijzelaar/opencv2.3/ubuntu oneiric main
 - deb-src http://ppa.launchpad.net/gijzelaar/opencv2.3/ubuntu oneiric main
 - sudo apt-get update -qq --allow-unauthenticated
 - sudo apt-get install -qq --allow-unauthenticated libcv-dev
node_js:
  - 0.6
  - 0.7
  - 0.8
  - 0.9
